export TRANSFORMERS_NO_PROGRESS_BAR=1
source ~/Environments/vestig/bin/activate
bash tests/test_m2_smoke.sh
bash tests/test_m3_smoke.sh
python3 tests/test_phase1_m3.py
python3 tests/test_phase2_m3.py
python3 tests/test_tracerank.py
python3 tests/test_tracerank_retrieval.py
python3 tests/test_m4_item1.py
python3 tests/test_m4_item2.py
python3 tests/test_m4_item3.py
python3 tests/test_m4_item4.py
python3 tests/test_m4_item5.py
python3 tests/test_m4_item6.py
python3 tests/test_ingest.py
bash tests/test_m4_smoke.sh
